apiVersion: v1
kind: List
items:
- apiVersion: kubevirt.io/v1
  kind: KubeVirt
  metadata:
    name: kubevirt
    namespace: kubevirt
  spec:
    configuration:
      developerConfiguration:
        featureGates:
        - Sidecar
        - NetworkBindingPlugins
      network:
        binding:
          kubedtnhack:
            networkAttachmentDefinition: kubedtnhack
- apiVersion: "k8s.cni.cncf.io/v1"
  kind: NetworkAttachmentDefinition
  metadata:
    name: kubedtnhack
  spec:
    config: '{ "cniVersion": "1.0.0", "name": "kubedtnhack", "plugins": [ { "type": "kubedtnhack" } ] }'
