apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubedtn-hack
  labels:
    app.kubernetes.io/name: daemonset
    app.kubernetes.io/instance: daemon
    app.kubernetes.io/component: daemon
    app.kubernetes.io/created-by: kube-dtn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kube-dtn
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: daemon
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: kubedtn-hack
        securityContext:
          privileged: true
        image: kubedtn-hack
        imagePullPolicy: IfNotPresent
        command: ["./entrypoint.sh"]
        resources:
          limits:
            cpu: 100m
            memory: 1G
        volumeMounts:
        - name: cni-cfg
          mountPath: /etc/cni/net.d
        - name: cni-bin
          mountPath: /opt/cni/bin
        - name: var-run-netns
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: sysfs
          mountPath: /sys/fs
          mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: cni-files
        hostPath:
          path: /opt/kubedtn
      - name: cni-cfg
        hostPath:
          path: /etc/cni/net.d
      - name: var-run-netns
        hostPath:
          path: /var/run/netns
      - name: sysfs
        hostPath:
          path: /sys/fs
