apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubedtn
# - enable-feature-gate.yaml
resources:
- kubedtn-hack.yaml
# - enable-feature-gate.yaml
images:
- name: kubedtn-hack
  newName: harbor.sail.se.sjtu.edu.cn/kubedtn/kubedtn-hack
  newTag: master-955eb15-59
